"""
Django settings for myapi project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8v@9g4p93%mv_98b_qb-#lahb63)8k2ik4mzwu)5gu3tlftgs@'

# SECURITY WARNING: don't run with debug turned on in production!


# Build ALLOWED_HOSTS from environment for flexible deployments (Render, Railway, etc.).
# Accept a comma-separated ALLOWED_HOSTS env var. If a scheme (http:// or https://) is
# provided, strip it so Django receives only the hostname.
def _normalize_host(h: str) -> str:
    h = h.strip()
    if not h:
        return ''
    # strip scheme if present
    if h.startswith('http://') or h.startswith('https://'):
        h = h.split('://', 1)[1]
    # strip any path
    return h.split('/', 1)[0]

raw_hosts = os.environ.get('ALLOWED_HOSTS')
if raw_hosts:
    DEBUG = False
    ALLOWED_HOSTS = [nh for nh in (_normalize_host(x) for x in raw_hosts.split(',')) if nh]
else:
    DEBUG = True
    # sensible defaults for local development and test client
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',
]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

GITHUB_CI = os.environ.get("GITHUB_ACTIONS") == "true"
LOCAL_ENV = os.environ.get("DJANGO_ENV") == "local"
DATABASE_URL = os.environ.get("DATABASE_URL")
print(DATABASE_URL)
# Default: SQLite (safe fallback)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}
try:
# 1️⃣ If DATABASE_URL exists (e.g., Render or Railway)
    if DATABASE_URL:
        DATABASES['default'] = dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,   # Keeps DB connection open for performance
            ssl_require=True    # Required for most cloud DBs
        )

    # 2️⃣ Local environment (PostgreSQL on localhost)
    elif LOCAL_ENV:
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'my_local_db'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }

    # 3️⃣ GitHub Actions (use SQLite)
    elif GITHUB_CI:
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / "test_db.sqlite3",
        }
except Exception as e:
    print("error in db connection", e)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# AUTH_USER_MODEL = "api.User"
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # React dev server
]


