import pytest
from rest_framework.test import APIClient
from django.urls import reverse
from api.models import User
from django.contrib.auth.hashers import make_password

@pytest.mark.django_db
def test_user_login():
    # Create user before login
    user = User.objects.create(
        email="sharma.vishal.2201@gmail.com",
        username="vishal",
        password=make_password("Vs42653@")
    )

    client = APIClient()
    url = reverse('user-login')  # generated by router basename='user'
    data = {
        "email": "sharma.vishal.2201@gmail.com",
        "password": "Vs42653@",
    }

    response = client.post(url, data, format='json')

    print(response.data)

    # ✅ login success returns 200, not 201
    assert response.status_code == 200
    assert response.data['message'] == "Login successful"
    assert response.data['user']['email'] == user.email
